### ISSUE TITLE
Peneus am Rand

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/xml#423]
* kursiv
* serifenlos
* mit é (`Penéus`)

Fälle: 
- [x] 6952 „fließt ein reicher Fluß“ geändert G in „fließt Peneios [Peneius MA 641] frey,“
- [x] 7001 „Peneus“ geändert in „Peneios“ G
- [x] #155 7153 zuerst „Peneus Pappeln“ moniert Ri geändert in „Des Pappelstromes“ G1 G
- [x] #247 7466 „Am untern Peneus“ moniert Ri, geändert in „Peneios rechts, lincks“ G1 G
- [x] vor 7495 „Peneus“ erg G1 geändert in „Peneios“ G ohne erkennbare Anweisung Riemers
- [x] 7495 „des Peneus Fluth“ moniert Ri („Penéus“ in der Zeile akzentuiert) geändert in „Peneios Fluth“ G
- [x] #157 #422 7743 „Peneus“ moniert Ri alR geändert G.
